### ISSUE TITLE
Add validation for scavenge/ephemeral that time does not exceed max time limit.

### ISSUE THREAD

**Issue by joecummings** [isi-vista/vista-pegasus-wrapper#63]

**Comment by joecummings** [comment]
OR, let the default wall-time be 1 hour. This will eliminate unspecified jobs from failing on any partition, BUT runs the risk of a lot more timeouts.

**Comment by LichMaster98** [comment]
I think I prefer validating that the time doesn't exceed max time. From a user perspective if the script fails to create the workflow because the user forgot to configure a wall-time for the job that's a quick fix as compared to letting the job go to the cluster and failing at one hour because the designer forgot to change the default wall-time.
